# Generated by Django 4.2.5 on 2023-09-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_m', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
